[package]
name = "yara-sys"
version = "0.5.0"
authors = ["Hugo Laloge <hugo.laloge@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Native bindings to the libyara library"
readme = "README.md"
repository = "https://github.com/Hugal31/yara-rust"
keywords = ["yara", "ffi"]
categories = ["external-ffi-bindings"]
links = "yara"
edition = "2018"

[features]
default = ["bindgen"]
bundled-3_8 = []
bundled-3_11 = []
vendored = ["yara-src"]

[build-dependencies]
bindgen = { version = "0.58", optional = true }
yara-src = { version = "0.1.2", optional = true }

[package.metadata.docs.rs]
no-default-features = true
features = ["bundled-3_11"]
